//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giay()
        {
            this.CTDatHangs = new HashSet<CTDatHang>();
        }
    
        public int MaGiay { get; set; }
        public string TenGiay { get; set; }
        public string HinhAnhGiay { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaMau { get; set; }
        public Nullable<int> MaAdmin { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<double> KichCo { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<System.DateTime> NgayHangVe { get; set; }
        public Nullable<int> SoDonHang { get; set; }
        public Nullable<int> Phai { get; set; }
        public Nullable<bool> Collection { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDatHang> CTDatHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
    }
}
